export const enum PathsToPage {
  HOME = '/themeforest',
  SOLUTIONS = '/solutions',
  SOLUTION = ':solutionId',
  ELEMENTS = '/elements',
  BLOG = '/blog',
  CONTACTS = '/contacts',
  ABOUT_US = '/about',
  TEAM = '/team',
  FAQ = '/faq',
  SERVICES = '/services',
  SERVICE = ':serviceId',
  MAP = '/map',
  PRICING = '/pricing',
}
